{
  "language": "java",
  "jdk": "oraclejdk8",
  "install": "mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 -DskipTests=true",
  "script": "mvn test -Dmaven.compiler.target=8 -Dmaven.compiler.source=8",
  "group": "stable",
  "dist": "trusty",
  "os": "windows"
  "addons":
  "apt":
    "sources":
      - google-chrome
    "packages":
      - google-chrome-beta
"before_install":
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - google-chrome-stable --headless --no-sandbox
}